# Generated by Django 5.1 on 2024-08-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_password_alter_user_created_at_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('code', models.CharField(editable=False, max_length=200)),
                ('level', models.IntegerField(max_length=10)),
                ('send_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
