# Generated by Django 5.1 on 2024-08-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_code_id_code_code_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='level',
        ),
    ]
