# Generated by Django 5.1 on 2024-08-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_code_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_output',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
