# Generated by Django 5.1 on 2024-08-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='level',
            new_name='level_id',
        ),
    ]
