# Generated by Django 5.1 on 2024-08-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_level_level_level_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='level_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='level',
            name='level_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
